recovery_vault_name                          = "vault-test"
resource_group_name                          = "test-rg"
resource_group_location                      = "eastasia"
recovery_vault_sku                           = "Standard"
backup_policy_name                           = "policy12"
backup_policy_instant_restore_retention_days = 5
backup_policy_backup_frequency               = "Daily"
backup_policy_backup_time                    = "23:00"
backup_policy_backup_weekdays                = ["Sunday", "Monday", "Tuesday"]
daily_retention                              = 9
backup_policy_retention_weekly_count         = 7
backup_policy_retention_weekly_weekdays      = ["Sunday", "Monday", "Tuesday"]
backup_policy_retention_monthly_count        = 2
backup_policy_retention_monthly_weekdays     = ["Sunday", "Monday", "Tuesday"]
backup_policy_retention_monthly_weeks        = ["First", "Second", "Third"]
backup_policy_retention_yearly_count         = 4
backup_policy_retention_yearly_weekdays      = ["Sunday", "Monday", "Tuesday"]
backup_policy_retention_yearly_weeks         = ["First", "Second", "Third"]
backup_policy_retention_yearly_months        = ["January", "March", "April", "May"]
virtual_machine_id                           = "/subscriptions/4c93ad0c-1cbc-4230-8418-f8df57418f3c/resourceGroups/deleteRG/providers/Microsoft.Compute/virtualMachines/deleteVM"